const _fl_str = (...xs) => xs.map(x => x==null?'':String(x)).join('');
const _fl_length = (x) => (x?x.length:0);
const _fl_get = (o,k,d) => { if(o==null)return d||null; let ks=String(k).startsWith(':')?k.slice(1):String(k); if(Array.isArray(o)){let idx=parseInt(ks);if(!isNaN(idx))return o[idx]!==undefined?o[idx]:(d||null);if(ks==='length')return o.length;} if(typeof o==='object'){if(o[ks]!==undefined)return o[ks];} return d||null; }
const _fl_null_q = (v) => v===null||v===undefined;
const _fl_keys = (o) => o?Object.keys(o):[];
const _fl_map_set = (o,k,v) => ({...o,[k]:v});
const _fl_has_key_q = (o,k) => o?(String(k) in o):false;
const _fl_append = (l,x) => [...(l||[]),x];
const list = (...args) => [...args];
const append = (l,x) => [...(l||[]),x];
const _fl_first = (l) => (l&&l.length>0)?l[0]:null;
const _fl_last = (l) => (l&&l.length>0)?l[l.length-1]:null;
const _fl_rest = (l) => (l&&l.length>0)?l.slice(1):[];
const _fl_slice = (l,a,b) => (l||[]).slice(a,b);
const _fl_map = (arr,fn) => (arr||[]).map(x=>fn(x));
const _fl_filter = (arr,fn) => (arr||[]).filter(x=>{const r=fn(x);return r!==false&&r!==null;});
const _fl_reduce = (arr,fn,init) => (arr||[]).reduce((a,x)=>fn(a,x),init);
const _fl_some = (f,l) => (l||[]).some(x=>f(x));
const _fl_every = (f,l) => (l||[]).every(x=>f(x));
const _fl_file_read = (p) => require('fs').readFileSync(p,'utf8');
const _fl_file_write = (p,c) => require('fs').writeFileSync(p,c);
const _fl_file_exists = (p) => require('fs').existsSync(p);
const _fl_file_delete = (p) => { try { require('fs').unlinkSync(p); } catch(e) {} };
const _fl_file_append = (p,c) => require('fs').appendFileSync(p,String(c));
const _fl_file_copy = (s,d) => require('fs').copyFileSync(s,d);
const _fl_file_rename = (o,n) => require('fs').renameSync(o,n);
const _fl_file_size = (p) => { try { return require('fs').statSync(p).size; } catch(e) { return 0; } };
const _fl_file_modified = (p) => { try { return require('fs').statSync(p).mtimeMs; } catch(e) { return 0; } };
const _fl_file_mkdir = (p) => { try { require('fs').mkdirSync(p,{recursive:true}); } catch(e) {} };
const _fl_file_rmdir = (p) => { try { require('fs').rmSync(p,{recursive:true,force:true}); } catch(e) {} };
const _fl_file_list = (p) => { try { return require('fs').readdirSync(p); } catch(e) { return []; } };
const _fl_process_run = (cmd) => { try { return require('child_process').execSync(cmd,{encoding:'utf8'}); } catch(e) { return ''; } };
const _fl_process_run_args = (cmd,args) => { try { return require('child_process').execSync(cmd+' '+(args||[]).join(' '),{encoding:'utf8'}); } catch(e) { return ''; } };
const _fl_process_exec = (cmd) => { try { return require('child_process').execSync(cmd,{encoding:'utf8'}); } catch(e) { return ''; } };
const _fl_process_exec_args = (cmd,args) => { try { return require('child_process').execSync(cmd+' '+(args||[]).join(' '),{encoding:'utf8'}); } catch(e) { return ''; } };
const _fl_process_spawn = (cmd,args) => { try { const r=require('child_process').spawnSync(cmd,args||[],{encoding:'utf8'}); return r.stdout||''; } catch(e) { return ''; } };
const _fl_process_kill = (pid) => { try { process.kill(pid); } catch(e) {} };
const _fl_process_wait = (pid) => null;
const _fl_env_get = (k) => process.env[k]||null;
const _fl_env_set = (k,v) => { process.env[k]=String(v); };
const _fl_env_all = () => process.env;
const _fl_file_is_file = (p) => { try { return require('fs').statSync(p).isFile(); } catch(e) { return false; } };
const _fl_file_is_dir = (p) => { try { return require('fs').statSync(p).isDirectory(); } catch(e) { return false; } };
const _fl_process_exists = (pid) => { try { process.kill(pid,0); return true; } catch(e) { return false; } };
const _fl_process_getcwd = () => process.cwd();
const _fl_process_chdir = (p) => { try { process.chdir(p); } catch(e) {} };
const _fl_process_pid = () => process.pid;
const _fl_process_ppid = () => process.ppid||null;
var file_read = (p) => _fl_file_read(String(p));
var file_write = (p,c) => _fl_file_write(String(p),String(c));
var file_exists = (p) => _fl_file_exists(String(p));
const _fl_get_argv = () => (typeof process!=='undefined'?process.argv.slice(2):[]);
const _fl_print = (v) => { console.log(v); return v; }
const null_q = _fl_null_q;
const some_q = _fl_some;
const every_q = _fl_every;
const cli_args = _fl_get_argv;
const get = _fl_get;
const keys = _fl_keys;
const has_key_q = _fl_has_key_q;
const slice = _fl_slice;
const first = _fl_first;
const last = _fl_last;
const rest = _fl_rest;
const map = (fn,arr) => (arr||[]).map(x=>fn(x));
const filter = (fn,arr) => (arr||[]).filter(x=>{const r=fn(x);return r!==false&&r!==null;});
const reduce = (fn,init,arr) => (arr||[]).reduce((a,x)=>fn(a,x),init);
const print = _fl_print;
const println = (v) => { console.log(v==null?'':String(v)); return v; }
var str_replace = (s,ov,nv) => { if(s==null)return ''; const st=String(s); return st.split(String(ov)).join(nv==null?'':String(nv)); };
const str_index_of = (s,sub) => (typeof s==='string'&&typeof sub==='string')?s.indexOf(sub):-1;
const index_of = str_index_of;
const str_slice = (s,a,b) => s?(b===undefined?s.slice(a):s.slice(a,b)):'';
const substring = str_slice;
const char_at = (s,i) => (s&&s[i])||null;
const char_code_at = (s,i) => typeof s==='string'?s.charCodeAt(i):0;
const trim = (s) => String(s||'').trim();
const starts_with_q = (s,p) => String(s||'').startsWith(String(p||''));
const ends_with_q = (s,sf) => String(s||'').endsWith(String(sf||''));
const replace = (s,ov,nv) => { if(s==null)return ''; const st=String(s); if(ov instanceof RegExp)return st.replace(ov,nv==null?'':String(nv)); return st.split(String(ov)).join(nv==null?'':String(nv)); };
const split = (s,sep) => String(s||'').split(sep);
const str_join = (arr,sep) => (arr||[]).join(sep===undefined?'':sep);
const join = str_join;
const concat = (a,b) => (Array.isArray(a)&&Array.isArray(b))?[...a,...b]:String(a||'')+String(b||'');
const push = (arr,v) => [...(arr||[]),v];
const pop = (arr) => (arr&&arr.length>0)?arr.slice(0,-1):[];
const reverse = (arr) => Array.isArray(arr)?[...arr].reverse():arr;
const sort_by = (arr,fn) => Array.isArray(arr)?[...arr].sort((a,b)=>fn(a)<fn(b)?-1:fn(a)>fn(b)?1:0):arr;
const flat_map = (arr,fn) => (arr||[]).flatMap(fn);
const range = (s,e) => { const r=[]; let st=e===undefined?0:s; let en=e===undefined?s:e; for(let i=st;i<en;i++)r.push(i); return r; };
const merge = (a,b) => Object.assign({},a,b);
const assoc = (o,k,v) => { const r=Object.assign({},o); const key=typeof k==='string'&&k.startsWith(':')?k.slice(1):String(k); r[key]=v; return r; };
const dissoc = (o,k) => { const r=Object.assign({},o); const key=typeof k==='string'&&k.startsWith(':')?k.slice(1):String(k); delete r[key]; return r; };
var map_entries = (m) => m instanceof Map?[...m.entries()]:(m&&typeof m==='object'&&!Array.isArray(m)?Object.entries(m):[]);
var map_keys = (m) => m instanceof Map?[...m.keys()]:(m&&typeof m==='object'&&!Array.isArray(m)?Object.keys(m):[]);
var map_values = (m) => m instanceof Map?[...m.values()]:(m&&typeof m==='object'&&!Array.isArray(m)?Object.values(m):[]);
const array_q = (v) => Array.isArray(v);
var list_q = (v) => Array.isArray(v);
var map_q = (v) => v!==null&&typeof v==='object'&&!Array.isArray(v);
var fn_q = (v) => typeof v==='function';
const number_q = (v) => typeof v==='number';
const string_q = (v) => typeof v==='string';
var str_upper = (s) => String(s||'').toUpperCase();
var str_lower = (s) => String(s||'').toLowerCase();
var str_contains = (s,sub) => String(s||'').includes(String(sub||''));
var str_starts_with = (s,p) => String(s||'').startsWith(String(p||''));
var str_ends_with = (s,sf) => String(s||'').endsWith(String(sf||''));
var str_trim = (s) => String(s||'').trim();
var str_length = (s) => String(s||'').length;
var str_split = (s,sep) => String(s||'').split(sep);
var take = (n,arr) => (arr||[]).slice(0,n);
var drop = (n,arr) => (arr||[]).slice(n);
var zip = (a,b) => { const r=[]; const l=Math.min((a||[]).length,(b||[]).length); for(let i=0;i<l;i++)r.push([a[i],b[i]]); return r; };
var flatten = (arr) => (arr||[]).flat();
var sort = (arr,fn) => fn?[...(arr||[])].sort((a,b)=>fn(a,b)?-1:1):[...(arr||[])].sort();
var math_sqrt = (n) => Math.sqrt(n);
var math_pi = Math.PI;
var unknown = (...a) => a[a.length-1];
function _fl_type_of(v) { if(v===null||v===undefined)return 'nil'; if(Array.isArray(v))return 'list'; return typeof v; }
const not = (v) => !v;
const abs = (n) => Math.abs(n);
const floor = (n) => Math.floor(n);
const ceil_val = (n) => Math.ceil(n);
const round = (n) => Math.round(n);
const max_val = (a,b) => a>b?a:b;
const min_val = (a,b) => a<b?a:b;
const error = (msg) => { throw new Error(String(msg)); };
const now_ms = () => Date.now();
const now_iso = () => new Date().toISOString();
const now_unix = () => Math.floor(Date.now()/1000);
const json_parse = (s) => { try{return JSON.parse(s);}catch(e){return null;} };
const json_stringify = (v) => JSON.stringify(v);
const shell_exec = (cmd,inp) => { try{const {execSync}=require('child_process');const opts={encoding:'utf8'};if(inp)opts.input=inp;return execSync(cmd,opts);}catch(e){return '';} };
const _fl_run_inherit = (cmd) => { require('child_process').spawnSync(cmd,{shell:true,stdio:'inherit'}); };
const __fl_routes = [];
const _fl_server_get = (path,fn) => { __fl_routes.push({method:'GET',path,fn}); };
const _fl_server_start = (port) => { const http=require('http'); http.createServer(async(req,res)=>{ const r=__fl_routes.find(r=>r.method===req.method&&r.path===require('url').parse(req.url).pathname); if(r){const result=await(typeof r.fn==='string'?eval(r.fn):r.fn)(req);res.end(String(result));}else{res.statusCode=404;res.end('Not Found');} }).listen(port);console.log('Server on '+port); };
const server_get = _fl_server_get;
const server_start = _fl_server_start;
var sum_field = (rows,field) => ((rows===null)?0:((len(rows)===0)?0:(to_number(get(first(rows),field,0))+sum_field(rest(rows),field))));
var sgis_population_result = (rows) => ({"value":sum_field(rows,"population"),"status":((sum_field(rows,"population")>0)?"실측":"데이터 미제공")});
var sgis_household_result = (rows,status) => ({"value":sum_field(rows,"household_cnt"),"status":((sum_field(rows,"household_cnt")>0)?status:"데이터 미제공")});
var sgis_age_codes_35_to_50 = () => "08,09,10";
var population_contract = (total,male35to50,households,one_person,family23,year,source) => ({"total-population":total,"male-35-to-50":male35to50,"households":households,"one-person":one_person,"family-2-to-3":family23,"reference-year":year,"source":source});
