// 상품 등록 단계에서는 아래 products 배열에 상품 객체를 추가합니다.
// image는 public 폴더 기준 경로 또는 https 이미지 주소를 사용할 수 있습니다.
export const productCategories = [
  { id: 'all', label: '전체 상품' },
  { id: 'chemical', label: '세차 케미컬' },
  { id: 'tool', label: '세차 도구' },
  { id: 'equipment', label: '장비·부품' },
  { id: 'safety', label: '안전·관리용품' },
];

export const products = [
  {
    id: 'k002-65',
    name: '셀프세차장 진공청소기 카본브러쉬',
    category: 'equipment',
    summary: '진공청소기 모터 전원공급용 카본브러쉬입니다.',
    price: 4400,
    image: 'https://k002.com/mall/shop_image/202005/motor11.jpg',
    shopUrl: 'https://k002.com/mall/m_mall_detail.php?ps_goid=65',
    badge: 'NEW',
    inStock: true,
    featured: 70,
  },
  {
    id: 'k002-64',
    name: '손세차장 진공청소기 습식모터',
    category: 'equipment',
    summary: '물이나 습기를 흡입해도 사용할 수 있는 습식 모터입니다.',
    price: 55000,
    image: 'https://k002.com/mall/shop_image/202005/motor1.jpg',
    shopUrl: 'https://k002.com/mall/m_mall_detail.php?ps_goid=64',
    inStock: true,
    featured: 60,
  },
  {
    id: 'k002-63',
    name: '셀프세차장 진공청소기 건식모터',
    category: 'equipment',
    summary: '일반 건식형 진공청소기에 사용하는 모터 제품입니다.',
    price: 55000,
    image: 'https://k002.com/mall/shop_image/202005/motor2.jpg',
    shopUrl: 'https://k002.com/mall/m_mall_detail.php?ps_goid=63',
    inStock: true,
    featured: 50,
  },
  {
    id: 'k002-62',
    name: '셀프세차장 세차솔대',
    category: 'tool',
    summary: '세차용 브러쉬를 결합해 사용하는 세차솔대입니다.',
    price: 20000,
    image: 'https://k002.com/mall/shop_image/202005/sum_600%286%29.jpg',
    shopUrl: 'https://k002.com/mall/m_mall_detail.php?ps_goid=62',
    inStock: true,
    featured: 40,
  },
  {
    id: 'k002-60',
    name: '고압세척기 압력게이지',
    category: 'equipment',
    summary: '고압세척기의 작동 압력을 확인하는 교체용 부속입니다.',
    price: 22000,
    image: 'https://k002.com/mall/shop_image/202005/sum_600%283%29.jpg',
    shopUrl: 'https://k002.com/mall/m_mall_detail.php?ps_goid=60',
    inStock: true,
    featured: 30,
  },
  {
    id: 'k002-58',
    name: '셀프세차장 필터 하우징',
    category: 'equipment',
    summary: '지하수 또는 수도에 연결해 이물질을 걸러주는 필터 하우징입니다.',
    price: 44000,
    image: 'https://k002.com/mall/shop_image/202005/sum_600.jpg',
    shopUrl: 'https://k002.com/mall/m_mall_detail.php?ps_goid=58',
    badge: 'SALE',
    inStock: true,
    featured: 80,
  },
  {
    id: 'k002-57',
    name: '셀프세차장 랜스형 인젝터',
    category: 'tool',
    summary: '랜스에 호스를 바로 연결해 폼세제를 사용할 수 있는 인젝터입니다.',
    price: 66000,
    image: 'https://k002.com/mall/shop_image/202005/sum_500.jpg',
    shopUrl: 'https://k002.com/mall/m_mall_detail.php?ps_goid=57',
    inStock: true,
    featured: 20,
  },
  {
    id: 'k002-51',
    name: 'XMTA 3.5G 22 고압펌프',
    category: 'equipment',
    summary: '안정적인 내구성을 강조한 셀프세차장용 고압펌프입니다.',
    price: 550000,
    image: 'https://k002.com/mall/shop_image/202004/sum_500%2812%29.jpg',
    shopUrl: 'https://k002.com/mall/m_mall_detail.php?ps_goid=51',
    badge: 'BEST',
    inStock: true,
    featured: 90,
  },
];

/*
상품 등록 예시
{
  id: 'sample-001',
  name: '상품명',
  category: 'chemical',
  summary: '상품을 한 줄로 소개합니다.',
  price: 25000,
  image: '/products/sample-001.webp',
  shopUrl: 'https://k002.com/mall/m_mall_detail.php?ps_goid=상품번호',
  badge: 'BEST',
  inStock: true,
  featured: 10,
}
*/
